image:
  file: .gitpod.Dockerfile

#tasks:
#  - init: >
#      make build
#    command: >
#      interview-accountapi

vscode:
  extensions:
    - premparihar.gotestexplorer@0.1.10:jvUM8akrQ67vQxfjaxCgCg==

ports:
  - port: 8080
    onOpen: ignore

checkoutLocation: "go/src/github.com/form3tech-oss/interview-accountapi-pair-programming"
workspaceLocation: "go/src/github.comform3tech-oss/interview-accountapi-pair-programming"
