version: '2'
services:
  accountapi:
    image: tech.form3/interview-accountapi:v0.1-1-g19364df5
    restart: on-failure
    links:
      - postgresql
      - vault
    depends_on:
      - postgresql
      - vault
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=8fb95528-57c6-422e-9722-d2147bcba8ed
      - STACK_NAME=f3-interview-accountapi
      - DATABASE-HOST=postgresql
      - DATABASE-USERNAME=interview_accountapi_user
      - DATABASE-PASSWORD=123
      - DATABASE-SSL-MODE=disable
    ports:
      - 8080:8080