/* #nosec */// Code generated by go-swagger; DO NOT EDIT.

package account_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/form3tech-oss/interview-accountapi-pair-programming/internal/swagger-client/interview-accountapi/models"
)

// GetOrganisationAccountsReader is a Reader for the GetOrganisationAccounts structure.
type GetOrganisationAccountsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrganisationAccountsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetOrganisationAccountsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetOrganisationAccountsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetOrganisationAccountsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetOrganisationAccountsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetOrganisationAccountsOK creates a GetOrganisationAccountsOK with default headers values
func NewGetOrganisationAccountsOK() *GetOrganisationAccountsOK {
	return &GetOrganisationAccountsOK{}
}

/*GetOrganisationAccountsOK handles this case with default header values.

List of accounts
*/
type GetOrganisationAccountsOK struct {
	Payload *models.AccountDetailsListResponse
}

func (o *GetOrganisationAccountsOK) Error() string {
	return fmt.Sprintf("[GET /organisation/accounts][%d] getOrganisationAccountsOK  %+v", 200, o.Payload)
}

func (o *GetOrganisationAccountsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccountDetailsListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganisationAccountsBadRequest creates a GetOrganisationAccountsBadRequest with default headers values
func NewGetOrganisationAccountsBadRequest() *GetOrganisationAccountsBadRequest {
	return &GetOrganisationAccountsBadRequest{}
}

/*GetOrganisationAccountsBadRequest handles this case with default header values.

Bad Request
*/
type GetOrganisationAccountsBadRequest struct {
	Payload *models.APIError
}

func (o *GetOrganisationAccountsBadRequest) Error() string {
	return fmt.Sprintf("[GET /organisation/accounts][%d] getOrganisationAccountsBadRequest  %+v", 400, o.Payload)
}

func (o *GetOrganisationAccountsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganisationAccountsForbidden creates a GetOrganisationAccountsForbidden with default headers values
func NewGetOrganisationAccountsForbidden() *GetOrganisationAccountsForbidden {
	return &GetOrganisationAccountsForbidden{}
}

/*GetOrganisationAccountsForbidden handles this case with default header values.

Forbidden
*/
type GetOrganisationAccountsForbidden struct {
	Payload *models.APIError
}

func (o *GetOrganisationAccountsForbidden) Error() string {
	return fmt.Sprintf("[GET /organisation/accounts][%d] getOrganisationAccountsForbidden  %+v", 403, o.Payload)
}

func (o *GetOrganisationAccountsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganisationAccountsInternalServerError creates a GetOrganisationAccountsInternalServerError with default headers values
func NewGetOrganisationAccountsInternalServerError() *GetOrganisationAccountsInternalServerError {
	return &GetOrganisationAccountsInternalServerError{}
}

/*GetOrganisationAccountsInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetOrganisationAccountsInternalServerError struct {
	Payload *models.APIError
}

func (o *GetOrganisationAccountsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /organisation/accounts][%d] getOrganisationAccountsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetOrganisationAccountsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
