/* #nosec */// Code generated by go-swagger; DO NOT EDIT.

package account_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOrganisationAccountsIDParams creates a new GetOrganisationAccountsIDParams object
// with the default values initialized.
func NewGetOrganisationAccountsIDParams() *GetOrganisationAccountsIDParams {
	var ()
	return &GetOrganisationAccountsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganisationAccountsIDParamsWithTimeout creates a new GetOrganisationAccountsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOrganisationAccountsIDParamsWithTimeout(timeout time.Duration) *GetOrganisationAccountsIDParams {
	var ()
	return &GetOrganisationAccountsIDParams{

		timeout: timeout,
	}
}

// NewGetOrganisationAccountsIDParamsWithContext creates a new GetOrganisationAccountsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOrganisationAccountsIDParamsWithContext(ctx context.Context) *GetOrganisationAccountsIDParams {
	var ()
	return &GetOrganisationAccountsIDParams{

		Context: ctx,
	}
}

// NewGetOrganisationAccountsIDParamsWithHTTPClient creates a new GetOrganisationAccountsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOrganisationAccountsIDParamsWithHTTPClient(client *http.Client) *GetOrganisationAccountsIDParams {
	var ()
	return &GetOrganisationAccountsIDParams{
		HTTPClient: client,
	}
}

/*GetOrganisationAccountsIDParams contains all the parameters to send to the API endpoint
for the get organisation accounts ID operation typically these are written to a http.Request
*/
type GetOrganisationAccountsIDParams struct {

	/*ID
	  Account Id

	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get organisation accounts ID params
func (o *GetOrganisationAccountsIDParams) WithTimeout(timeout time.Duration) *GetOrganisationAccountsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organisation accounts ID params
func (o *GetOrganisationAccountsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organisation accounts ID params
func (o *GetOrganisationAccountsIDParams) WithContext(ctx context.Context) *GetOrganisationAccountsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organisation accounts ID params
func (o *GetOrganisationAccountsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organisation accounts ID params
func (o *GetOrganisationAccountsIDParams) WithHTTPClient(client *http.Client) *GetOrganisationAccountsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organisation accounts ID params
func (o *GetOrganisationAccountsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get organisation accounts ID params
func (o *GetOrganisationAccountsIDParams) WithID(id strfmt.UUID) *GetOrganisationAccountsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get organisation accounts ID params
func (o *GetOrganisationAccountsIDParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganisationAccountsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
