/* #nosec */// Code generated by go-swagger; DO NOT EDIT.

package account_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/form3tech-oss/interview-accountapi-pair-programming/internal/swagger-client/interview-accountapi/models"
)

// NewPostOrganisationAccountsParams creates a new PostOrganisationAccountsParams object
// with the default values initialized.
func NewPostOrganisationAccountsParams() *PostOrganisationAccountsParams {
	var ()
	return &PostOrganisationAccountsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostOrganisationAccountsParamsWithTimeout creates a new PostOrganisationAccountsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostOrganisationAccountsParamsWithTimeout(timeout time.Duration) *PostOrganisationAccountsParams {
	var ()
	return &PostOrganisationAccountsParams{

		timeout: timeout,
	}
}

// NewPostOrganisationAccountsParamsWithContext creates a new PostOrganisationAccountsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostOrganisationAccountsParamsWithContext(ctx context.Context) *PostOrganisationAccountsParams {
	var ()
	return &PostOrganisationAccountsParams{

		Context: ctx,
	}
}

// NewPostOrganisationAccountsParamsWithHTTPClient creates a new PostOrganisationAccountsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostOrganisationAccountsParamsWithHTTPClient(client *http.Client) *PostOrganisationAccountsParams {
	var ()
	return &PostOrganisationAccountsParams{
		HTTPClient: client,
	}
}

/*PostOrganisationAccountsParams contains all the parameters to send to the API endpoint
for the post organisation accounts operation typically these are written to a http.Request
*/
type PostOrganisationAccountsParams struct {

	/*CreationRequest*/
	CreationRequest *models.AccountCreation

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post organisation accounts params
func (o *PostOrganisationAccountsParams) WithTimeout(timeout time.Duration) *PostOrganisationAccountsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post organisation accounts params
func (o *PostOrganisationAccountsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post organisation accounts params
func (o *PostOrganisationAccountsParams) WithContext(ctx context.Context) *PostOrganisationAccountsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post organisation accounts params
func (o *PostOrganisationAccountsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post organisation accounts params
func (o *PostOrganisationAccountsParams) WithHTTPClient(client *http.Client) *PostOrganisationAccountsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post organisation accounts params
func (o *PostOrganisationAccountsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreationRequest adds the creationRequest to the post organisation accounts params
func (o *PostOrganisationAccountsParams) WithCreationRequest(creationRequest *models.AccountCreation) *PostOrganisationAccountsParams {
	o.SetCreationRequest(creationRequest)
	return o
}

// SetCreationRequest adds the creationRequest to the post organisation accounts params
func (o *PostOrganisationAccountsParams) SetCreationRequest(creationRequest *models.AccountCreation) {
	o.CreationRequest = creationRequest
}

// WriteToRequest writes these params to a swagger request
func (o *PostOrganisationAccountsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CreationRequest != nil {
		if err := r.SetBodyParam(o.CreationRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
