/* #nosec */// Code generated by go-swagger; DO NOT EDIT.

package account_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/form3tech-oss/interview-accountapi-pair-programming/internal/swagger-client/interview-accountapi-pair-programming/models"
)

// PostOrganisationAccountsReader is a Reader for the PostOrganisationAccounts structure.
type PostOrganisationAccountsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostOrganisationAccountsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostOrganisationAccountsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostOrganisationAccountsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostOrganisationAccountsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewPostOrganisationAccountsConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPostOrganisationAccountsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostOrganisationAccountsCreated creates a PostOrganisationAccountsCreated with default headers values
func NewPostOrganisationAccountsCreated() *PostOrganisationAccountsCreated {
	return &PostOrganisationAccountsCreated{}
}

/*PostOrganisationAccountsCreated handles this case with default header values.

creation response
*/
type PostOrganisationAccountsCreated struct {
	Payload *models.AccountCreationResponse
}

func (o *PostOrganisationAccountsCreated) Error() string {
	return fmt.Sprintf("[POST /organisation/accounts][%d] postOrganisationAccountsCreated  %+v", 201, o.Payload)
}

func (o *PostOrganisationAccountsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccountCreationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostOrganisationAccountsBadRequest creates a PostOrganisationAccountsBadRequest with default headers values
func NewPostOrganisationAccountsBadRequest() *PostOrganisationAccountsBadRequest {
	return &PostOrganisationAccountsBadRequest{}
}

/*PostOrganisationAccountsBadRequest handles this case with default header values.

Bad Request
*/
type PostOrganisationAccountsBadRequest struct {
	Payload *models.APIError
}

func (o *PostOrganisationAccountsBadRequest) Error() string {
	return fmt.Sprintf("[POST /organisation/accounts][%d] postOrganisationAccountsBadRequest  %+v", 400, o.Payload)
}

func (o *PostOrganisationAccountsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostOrganisationAccountsForbidden creates a PostOrganisationAccountsForbidden with default headers values
func NewPostOrganisationAccountsForbidden() *PostOrganisationAccountsForbidden {
	return &PostOrganisationAccountsForbidden{}
}

/*PostOrganisationAccountsForbidden handles this case with default header values.

Forbidden
*/
type PostOrganisationAccountsForbidden struct {
	Payload *models.APIError
}

func (o *PostOrganisationAccountsForbidden) Error() string {
	return fmt.Sprintf("[POST /organisation/accounts][%d] postOrganisationAccountsForbidden  %+v", 403, o.Payload)
}

func (o *PostOrganisationAccountsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostOrganisationAccountsConflict creates a PostOrganisationAccountsConflict with default headers values
func NewPostOrganisationAccountsConflict() *PostOrganisationAccountsConflict {
	return &PostOrganisationAccountsConflict{}
}

/*PostOrganisationAccountsConflict handles this case with default header values.

Conflict
*/
type PostOrganisationAccountsConflict struct {
	Payload *models.APIError
}

func (o *PostOrganisationAccountsConflict) Error() string {
	return fmt.Sprintf("[POST /organisation/accounts][%d] postOrganisationAccountsConflict  %+v", 409, o.Payload)
}

func (o *PostOrganisationAccountsConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostOrganisationAccountsInternalServerError creates a PostOrganisationAccountsInternalServerError with default headers values
func NewPostOrganisationAccountsInternalServerError() *PostOrganisationAccountsInternalServerError {
	return &PostOrganisationAccountsInternalServerError{}
}

/*PostOrganisationAccountsInternalServerError handles this case with default header values.

Internal Server Error
*/
type PostOrganisationAccountsInternalServerError struct {
	Payload *models.APIError
}

func (o *PostOrganisationAccountsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /organisation/accounts][%d] postOrganisationAccountsInternalServerError  %+v", 500, o.Payload)
}

func (o *PostOrganisationAccountsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
